content:
  - name: Data
    label: Data
    type: collection
    path: _data
    view:
      fields: [ title, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: date, label: Date, type: date, options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" } }
      - { name: data, label: Data, type: code, options: { language: json  } }
      - name: stock
        label: Stock
        type: object
        fields:
          - name: code
            label: Code
            type: number
          - name: name
            label: Name
            type: string