content:
  - name: Data
    label: Data
    type: collection
    path: _data
    view:
      fields: [ title ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: data, label: Data, type: text }