content:
  - name: Data
    label: Data
    type: collection
    path: _data
    view:
      fields: [ title, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: date, label: Date, type: date, options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" } }
      - { name: data, label: Data, type: text }